services:
  blazor-app:
    image: blazor-cms
    container_name: meu-site-blazor
    volumes:
      - /mnt/projeto/data:/app/data
    networks:
      - projeto-rede
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    networks:
      - projeto-rede
    restart: always
    command: tunnel run --token eyJhIjoiMjRiOGNmZGM3N2IyMGFiMmNlMDUzZDIwY2Q5MDlmOTQiLCJ0IjoiMGZmNGU5MWQtZWJlMC00NDU5LThlZjYtY2I0M2M5YTU1MWU3IiwicyI6Ill6SmtZVEk1WVdNdFkyWXlOaTAwTW1SakxUazFZVGd0T0Roa1kyRmtOVGd3WlRSaSJ9

networks:
  projeto-rede:
    driver: bridge
