INSERT INTO Story (Id, Nome, Image, Descricao, Capitulo)
VALUES
    (1, 'Padrao', NULL, NULL, 0),
    (2, 'Natureza', 'seres-vivos.jpg', 'Esta história conta sobre todos os seres vivos do planeta terra', 1),
    (4, 'Moda', 'moda.jpg', 'Esta história conta sobre roupas, chapeus, bones, calçados, e todos os outros produtos relacionados a moda', 2),
    (5, 'veiculos', 'veiculo.jpg', 'Esta história conta sobre produtos desde a sua matéria-prima até o produto final (veiculos).', 3),
    (6, 'materiais de construção', 'Material.png', 'Esta história conta sobre todos os produtos relacionados a materiais de construção desde a matéria-prima até seu produto final.', 4),
    (7, 'alimentos e bebidas', 'alimentos.jpg', 'Esta história conta sobre todos os produtos relacionados a alimentos.', 7),
    (9, 'entretenimento', 'entretenimento.jpg', 'Esta história conta sobre todos os jogos de video-game e diversidades e entretenimento.', 8),
    (14, 'cosmeticos', 'cosmeticos.jpg', 'Esta história conta...', 9),
    (15, 'tecnologia', 'tecnologia.jpg', 'Esta história conta...', 10),
    (19, 'saúde e bem-star', 'saude.jpg', 'Esta história conta...', 12),
    (21, 'colecionáveis', 'colecionaveis.jpg', 'Esta história conta...', 13),
    (22, 'imóveis', 'imoveis.jpg', 'Esta história conta...', 6),
    (25, 'Estudos e Material Escolar', 'estudos.png', 'Esta história conta...', 15),
    (29, 'Blog e Vlog', 'blog.png', 'Esta história conta...', 17),
    (32, 'noticias urgentes', 'noticia.jpg', 'Esta história conta...', 19),
    (33, 'agronegócios', 'agronegocio.jpg', 'Esta história conta...', 20),
    (34, 'empresas', 'empresa.jpg', 'Esta história conta...', 18),
    (35, 'casa completa', 'casa.jpg', 'Esta história conta...', 5),
    (45, 'info-produtos', 'info-produto.jpg', 'Esta história conta...', 11),
    (47, 'Arte', 'arte.jpg', 'Esta história conta...', 14),
    (48, 'Projetos e obras', 'projeto.jpg', 'Esta história conta...', 21),
    (49, 'Serviços', 'serviço.jpg', 'Esta história conta...', 22),
    (51, 'Segurança', 'segurança.jpg', 'Esta história conta...', 16);

