SELECT TOP (1000) [Id]
      ,[Data]
      ,[Titulo]
      ,[StoryId]
      ,[LivroId]
      ,[Rotas]
      ,[Html]
      ,[Link]
      ,[TextoLink]
      ,[Discriminator]
      ,[ContentId]
      ,[Versiculo]
      ,[UserModelId]
  FROM [cms].[dbo].[Content]