// <auto-generated />
using System;
using BlazorServerCms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerCms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231025190229_QuantidadePorType")]
    partial class QuantidadePorType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("business.business.Classificacao", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("preferencia1")
                        .HasColumnType("int");

                    b.Property<int>("preferencia10")
                        .HasColumnType("int");

                    b.Property<int>("preferencia2")
                        .HasColumnType("int");

                    b.Property<int>("preferencia3")
                        .HasColumnType("int");

                    b.Property<int>("preferencia4")
                        .HasColumnType("int");

                    b.Property<int>("preferencia5")
                        .HasColumnType("int");

                    b.Property<int>("preferencia6")
                        .HasColumnType("int");

                    b.Property<int>("preferencia7")
                        .HasColumnType("int");

                    b.Property<int>("preferencia8")
                        .HasColumnType("int");

                    b.Property<int>("preferencia9")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classificacao");
                });

            modelBuilder.Entity("business.business.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("business.business.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("business.business.FiltroPagina", b =>
                {
                    b.Property<long>("FiltroId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaginaId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadePorType")
                        .HasColumnType("int");

                    b.HasKey("FiltroId", "PaginaId");

                    b.HasIndex("PaginaId");

                    b.ToTable("FiltroPagina");
                });

            modelBuilder.Entity("business.business.Rota", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Registrado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rota");
                });

            modelBuilder.Entity("business.business.savedFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FiltroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FiltroId");

                    b.ToTable("savedFolder");
                });

            modelBuilder.Entity("business.business.UserBook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook");
                });

            modelBuilder.Entity("business.business.UserBook1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook1");
                });

            modelBuilder.Entity("business.business.UserBook10", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook10");
                });

            modelBuilder.Entity("business.business.UserBook2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook2");
                });

            modelBuilder.Entity("business.business.UserBook3", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook3");
                });

            modelBuilder.Entity("business.business.UserBook4", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook4");
                });

            modelBuilder.Entity("business.business.UserBook5", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook5");
                });

            modelBuilder.Entity("business.business.UserBook6", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook6");
                });

            modelBuilder.Entity("business.business.UserBook7", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook7");
                });

            modelBuilder.Entity("business.business.UserBook8", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook8");
                });

            modelBuilder.Entity("business.business.UserBook9", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("LivroId")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("UserBook9");
                });

            modelBuilder.Entity("business.Comentario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<long>("IdPagina")
                        .HasColumnType("bigint");

                    b.Property<int>("Verso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("business.Compartilhante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Admin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comissao")
                        .HasColumnType("int");

                    b.Property<string>("CupomDesconto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Livro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Compartilhante");
                });

            modelBuilder.Entity("business.Filtro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Filtro");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Filtro");
                });

            modelBuilder.Entity("business.Group.Story", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Comentario")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaginaPadraoLink")
                        .HasColumnType("int");

                    b.Property<bool>("Produto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("business.ImagemProduto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ArquivoImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("WidthImagem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ImagemProduto");
                });

            modelBuilder.Entity("business.ItemPedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("business.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<bool>("Compartilhando")
                        .HasColumnType("bit");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("business.Pagina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("Comentario")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Pagina");
                });

            modelBuilder.Entity("business.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("business.Produto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("business.Telefone", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDD_Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDD_Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("business.VideoIncorporado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ArquivoVideoIncorporado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VideoIncorporado");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("business.Group.CamadaDez", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("CamadaNoveId")
                        .HasColumnType("bigint");

                    b.HasIndex("CamadaNoveId");

                    b.HasDiscriminator().HasValue("CamadaDez");
                });

            modelBuilder.Entity("business.Group.CamadaNove", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("CamadaOitoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CamadaOitoId");

                    b.HasDiscriminator().HasValue("CamadaNove");
                });

            modelBuilder.Entity("business.Group.CamadaOito", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("CamadaSeteId")
                        .HasColumnType("bigint");

                    b.HasIndex("CamadaSeteId");

                    b.HasDiscriminator().HasValue("CamadaOito");
                });

            modelBuilder.Entity("business.Group.CamadaSeis", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("SubSubGrupoId")
                        .HasColumnType("bigint");

                    b.HasIndex("SubSubGrupoId");

                    b.HasDiscriminator().HasValue("CamadaSeis");
                });

            modelBuilder.Entity("business.Group.CamadaSete", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("CamadaSeisId")
                        .HasColumnType("bigint");

                    b.HasIndex("CamadaSeisId");

                    b.HasDiscriminator().HasValue("CamadaSete");
                });

            modelBuilder.Entity("business.Group.Grupo", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("SubStoryId")
                        .HasColumnType("bigint");

                    b.HasIndex("SubStoryId");

                    b.HasDiscriminator().HasValue("Grupo");
                });

            modelBuilder.Entity("business.Group.SubGrupo", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.HasIndex("GrupoId");

                    b.HasDiscriminator().HasValue("SubGrupo");
                });

            modelBuilder.Entity("business.Group.SubStory", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.HasDiscriminator().HasValue("SubStory");
                });

            modelBuilder.Entity("business.Group.SubSubGrupo", b =>
                {
                    b.HasBaseType("business.Filtro");

                    b.Property<long>("SubGrupoId")
                        .HasColumnType("bigint");

                    b.HasIndex("SubGrupoId");

                    b.HasDiscriminator().HasValue("SubSubGrupo");
                });

            modelBuilder.Entity("business.business.Classificacao", b =>
                {
                    b.HasOne("business.Pagina", "Pagina")
                        .WithOne("Classificacao")
                        .HasForeignKey("business.business.Classificacao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("business.business.Endereco", b =>
                {
                    b.HasOne("business.business.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("business.business.Endereco", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("business.business.FiltroPagina", b =>
                {
                    b.HasOne("business.Filtro", "Filtro")
                        .WithMany("Pagina")
                        .HasForeignKey("FiltroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("business.Pagina", "Pagina")
                        .WithMany("Filtro")
                        .HasForeignKey("PaginaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filtro");

                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("business.business.savedFolder", b =>
                {
                    b.HasOne("business.Filtro", "Filtro")
                        .WithMany("savedFolder")
                        .HasForeignKey("FiltroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filtro");
                });

            modelBuilder.Entity("business.business.UserBook", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook1", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook10", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook2", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook3", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook4", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook5", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook6", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook7", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook8", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.business.UserBook9", b =>
                {
                    b.HasOne("business.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("business.Filtro", b =>
                {
                    b.HasOne("business.Group.Story", "Story")
                        .WithMany("Filtro")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("business.ImagemProduto", b =>
                {
                    b.HasOne("business.Produto", "Produto")
                        .WithMany("Imagem")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("business.ItemPedido", b =>
                {
                    b.HasOne("business.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("business.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("business.Pagina", b =>
                {
                    b.HasOne("business.Group.Story", "Story")
                        .WithMany("Pagina")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("business.Pedido", b =>
                {
                    b.HasOne("business.business.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("business.Produto", b =>
                {
                    b.HasOne("business.Pagina", "Pagina")
                        .WithOne("Produto")
                        .HasForeignKey("business.Produto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("business.Telefone", b =>
                {
                    b.HasOne("business.business.Cliente", "Cliente")
                        .WithOne("Telefone")
                        .HasForeignKey("business.Telefone", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("business.Group.CamadaDez", b =>
                {
                    b.HasOne("business.Group.CamadaNove", "CamadaNove")
                        .WithMany("CamadaDez")
                        .HasForeignKey("CamadaNoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamadaNove");
                });

            modelBuilder.Entity("business.Group.CamadaNove", b =>
                {
                    b.HasOne("business.Group.CamadaOito", "CamadaOito")
                        .WithMany("CamadaNove")
                        .HasForeignKey("CamadaOitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamadaOito");
                });

            modelBuilder.Entity("business.Group.CamadaOito", b =>
                {
                    b.HasOne("business.Group.CamadaSete", "CamadaSete")
                        .WithMany("CamadaOito")
                        .HasForeignKey("CamadaSeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamadaSete");
                });

            modelBuilder.Entity("business.Group.CamadaSeis", b =>
                {
                    b.HasOne("business.Group.SubSubGrupo", "SubSubGrupo")
                        .WithMany("CamadaSeis")
                        .HasForeignKey("SubSubGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubSubGrupo");
                });

            modelBuilder.Entity("business.Group.CamadaSete", b =>
                {
                    b.HasOne("business.Group.CamadaSeis", "CamadaSeis")
                        .WithMany("CamadaSete")
                        .HasForeignKey("CamadaSeisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamadaSeis");
                });

            modelBuilder.Entity("business.Group.Grupo", b =>
                {
                    b.HasOne("business.Group.SubStory", "SubStory")
                        .WithMany("Grupo")
                        .HasForeignKey("SubStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubStory");
                });

            modelBuilder.Entity("business.Group.SubGrupo", b =>
                {
                    b.HasOne("business.Group.Grupo", "Grupo")
                        .WithMany("SubGrupo")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("business.Group.SubSubGrupo", b =>
                {
                    b.HasOne("business.Group.SubGrupo", "SubGrupo")
                        .WithMany("SubSubGrupo")
                        .HasForeignKey("SubGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubGrupo");
                });

            modelBuilder.Entity("business.business.Cliente", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("business.Filtro", b =>
                {
                    b.Navigation("Pagina");

                    b.Navigation("savedFolder");
                });

            modelBuilder.Entity("business.Group.Story", b =>
                {
                    b.Navigation("Filtro");

                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("business.Pagina", b =>
                {
                    b.Navigation("Classificacao");

                    b.Navigation("Filtro");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("business.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("business.Produto", b =>
                {
                    b.Navigation("Imagem");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("business.Group.CamadaNove", b =>
                {
                    b.Navigation("CamadaDez");
                });

            modelBuilder.Entity("business.Group.CamadaOito", b =>
                {
                    b.Navigation("CamadaNove");
                });

            modelBuilder.Entity("business.Group.CamadaSeis", b =>
                {
                    b.Navigation("CamadaSete");
                });

            modelBuilder.Entity("business.Group.CamadaSete", b =>
                {
                    b.Navigation("CamadaOito");
                });

            modelBuilder.Entity("business.Group.Grupo", b =>
                {
                    b.Navigation("SubGrupo");
                });

            modelBuilder.Entity("business.Group.SubGrupo", b =>
                {
                    b.Navigation("SubSubGrupo");
                });

            modelBuilder.Entity("business.Group.SubStory", b =>
                {
                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("business.Group.SubSubGrupo", b =>
                {
                    b.Navigation("CamadaSeis");
                });
#pragma warning restore 612, 618
        }
    }
}
